Prototype frontend. Missing search button.
BenignPhantasm/youtube_transcript_search pull request #2
Opened 2023-12-20 08:04 UTC by NodeReplacer

2023-12-20 11:08 UTC, NodeReplacer commented
Updated the pull request with functioning search button (that moves to a search page that doesn't have anything there except a hyperlink linking back to the home page, but still. We can fill in the search logic later.)

And also make it look better later.

2023-12-20 21:29 UTC, BenignPhantasm requested changes
Just a couple of changes

2023-12-20 21:43 UTC, BenignPhantasm commented on app/assets/stylesheets/home.css
> +@import 'materialize';
I'm not sure if this is right. Can you use one of the `material` buttons in the view just to prove that it's working properly?

2023-12-21 05:09 UTC, BenignPhantasm approved these changes
Nice work!

2023-12-21 05:09 UTC, merged